// Robot Admin AI OS V67.9 MEGA SAFE NativeActivity host
// Direct V65.8 proven base only: avoid nested wrapper chains.
#define ANativeActivity_onCreate ANativeActivity_onCreate_v658_legacy
#include "native_activity_host_v658.cpp"
#undef ANativeActivity_onCreate
#include <android/asset_manager.h>
#include <atomic>
#include <string>
#include <thread>

namespace {
std::atomic<bool> run679{false};
std::atomic<int> page679{0},touch679{0};
AInputQueue* iq679=nullptr; ANativeWindow* win679=nullptr; std::thread th679; int W679=0,H679=0;
enum {HOME=0,VERIFY=1,FILES=2,TASKS=3,DATA=4,AUDIT=5,ERRORS=6};
const char* title679(int p){switch(p){case VERIFY:return"V67.4 TRUSTED VERIFY";case FILES:return"V67.5 FILE BROWSER RO";case TASKS:return"V67.6 TASK PARSER RO";case DATA:return"V67.7 CSV ANALYZER PRO";case AUDIT:return"V67.9 BACKUP AUDIT RO";case ERRORS:return"V67.8 ERROR INTELLIGENCE";default:return"V67.9 MEGA SAFE BUNDLE";}}
bool draw679(ANativeWindow*w){if(!w)return false;EGLDisplay d=eglGetDisplay(EGL_DEFAULT_DISPLAY);if(d==EGL_NO_DISPLAY||!eglInitialize(d,nullptr,nullptr))return false;const EGLint ca[]={EGL_SURFACE_TYPE,EGL_WINDOW_BIT,EGL_RENDERABLE_TYPE,EGL_OPENGL_ES2_BIT,EGL_RED_SIZE,8,EGL_GREEN_SIZE,8,EGL_BLUE_SIZE,8,EGL_NONE};EGLConfig c=nullptr;EGLint n=0;if(!eglChooseConfig(d,ca,&c,1,&n)||n<1){eglTerminate(d);return false;}EGLint f=0;eglGetConfigAttrib(d,c,EGL_NATIVE_VISUAL_ID,&f);ANativeWindow_setBuffersGeometry(w,0,0,f);EGLSurface su=eglCreateWindowSurface(d,c,w,nullptr);const EGLint xa[]={EGL_CONTEXT_CLIENT_VERSION,2,EGL_NONE};EGLContext x=eglCreateContext(d,c,EGL_NO_CONTEXT,xa);if(su==EGL_NO_SURFACE||x==EGL_NO_CONTEXT||!eglMakeCurrent(d,su,su,x)){if(x!=EGL_NO_CONTEXT)eglDestroyContext(d,x);if(su!=EGL_NO_SURFACE)eglDestroySurface(d,su);eglTerminate(d);return false;}EGLint W=0,H=0;eglQuerySurface(d,su,EGL_WIDTH,&W);eglQuerySurface(d,su,EGL_HEIGHT,&H);W679=W;H679=H;glViewport(0,0,W,H);glClearColor(.025f,.07f,.15f,1);glClear(GL_COLOR_BUFFER_BIT);int s=W/310;if(s<3)s=3;if(s>5)s=5;int lx=5*s,rx=W/2+14*s,top=H-20*s,row=8*s,p=page679.load();text("ROBOT ADMIN AI OS",lx,top,s,.92f,.96f,1);text("V67.9 MEGA SAFE",rx,top,s,.6f,.75f,.95f);text("CPP CORE: READY",lx,top-row,s,.35f,.9f,.55f);text("SAFETY: LOCKED",rx,top-row,s,.35f,.9f,.55f);text("MODE: OFFLINE FIRST",lx,top-2*row,s,.75f,.85f,.95f);text("CONTROL: READ ONLY",rx,top-2*row,s,.75f,.85f,.95f);text("LOCKED BASE: V67.1",lx,top-3*row,s,.55f,.8f,.95f);text("TOUCH: "+std::to_string(touch679.load()),lx,top-4*row,s,.55f,.8f,.95f);
// Dedicated right safety column with non-overlapping vertical positions.
text("WRITE: OFF",rx,top-3*row,s,.95f,.55f,.3f);text("DELETE: OFF",rx,top-4*row,s,.95f,.55f,.3f);text("RESTORE: OFF",rx,top-5*row,s,.95f,.55f,.3f);text("APPLY: OFF",rx,top-6*row,s,.95f,.55f,.3f);text("LIVE ORDERS: OFF",rx,top-7*row,s,.95f,.55f,.3f);text("AUTO UPDATE: OFF",rx,top-8*row,s,.95f,.55f,.3f);text("PROD GATE: CLOSED",rx,top-9*row,s,.95f,.55f,.3f);
int py=top-6*row;text(title679(p),lx,py,s,.35f,.9f,.55f);if(p==HOME){text("MODULES: V67.4 - V67.9",lx,py-row,s,.75f,.85f,.95f);text("VERIFY / FILES / TASKS",lx,py-2*row,s,.75f,.85f,.95f);text("CSV / ERRORS / BACKUP AUDIT",lx,py-3*row,s,.75f,.85f,.95f);text("MUTATIONS: BLOCKED",lx,py-4*row,s,.95f,.55f,.3f);}else if(p==VERIFY){text("SHA256: EXPECTED VS ACTUAL",lx,py-row,s,.75f,.85f,.95f);text("RESULT: MATCH / FAIL / MISSING",lx,py-2*row,s,.75f,.85f,.95f);text("RESTORE: BLOCKED",lx,py-3*row,s,.95f,.55f,.3f);}else if(p==FILES){text("APK ASSETS + APP SANDBOX",lx,py-row,s,.75f,.85f,.95f);text("MAX ENTRIES: 128",lx,py-2*row,s,.75f,.85f,.95f);text("WRITE / DELETE / RENAME: BLOCKED",lx,py-3*row,s,.95f,.55f,.3f);}else if(p==TASKS){text("ID / PRIORITY / STATUS / NOTE",lx,py-row,s,.75f,.85f,.95f);text("MAX TASKS: 128",lx,py-2*row,s,.75f,.85f,.95f);text("EXECUTE / APPLY: BLOCKED",lx,py-3*row,s,.95f,.55f,.3f);}else if(p==DATA){text("MIN / MAX / AVG",lx,py-row,s,.75f,.85f,.95f);text("INVALID + DUPLICATE ROWS",lx,py-2*row,s,.75f,.85f,.95f);text("WRITE / REPAIR: BLOCKED",lx,py-3*row,s,.95f,.55f,.3f);}else if(p==ERRORS){text("CODE + REASON + SAFE ACTION",lx,py-row,s,.75f,.85f,.95f);text("AUTO FIX: BLOCKED",lx,py-2*row,s,.95f,.55f,.3f);}else{text("VERIFIED / UNVERIFIED",lx,py-row,s,.75f,.85f,.95f);text("FAILED / MISSING",lx,py-2*row,s,.75f,.85f,.95f);text("RESTORE / APPLY: BLOCKED",lx,py-3*row,s,.95f,.55f,.3f);}int gap=2*s,bh=13*s,by=3*s,bw=(W-8*gap)/7;const char*bn[7]={"HOME","VERIFY","FILES","TASKS","DATA","AUDIT","ERROR"};for(int i=0;i<7;i++){float gg=(p==i)?.48f:.27f;rect(gap+i*(bw+gap),by,bw,bh,.08f,gg,.28f);text(bn[i],gap+i*(bw+gap)+s,by+4*s,s,.92f,.96f,1);}eglSwapBuffers(d,su);eglMakeCurrent(d,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);eglDestroyContext(d,x);eglDestroySurface(d,su);eglTerminate(d);return true;}
int cb679(int,int,void*){if(!iq679)return 1;AInputEvent*e=nullptr;while(AInputQueue_getEvent(iq679,&e)>=0){if(AInputQueue_preDispatchEvent(iq679,e))continue;int h=0;if(AInputEvent_getType(e)==AINPUT_EVENT_TYPE_MOTION&&(AMotionEvent_getAction(e)&AMOTION_EVENT_ACTION_MASK)==AMOTION_EVENT_ACTION_UP){float px=AMotionEvent_getX(e,0),py=(float)H679-AMotionEvent_getY(e,0);int s=W679/310;if(s<3)s=3;if(s>5)s=5;int gap=2*s,bh=13*s,bw=(W679-8*gap)/7;if(py>=3*s&&py<=3*s+bh)for(int i=0;i<7;i++){int bx=gap+i*(bw+gap);if(px>=bx&&px<=bx+bw){page679=i;touch679++;h=1;break;}}}else if(AInputEvent_getType(e)==AINPUT_EVENT_TYPE_KEY&&AKeyEvent_getAction(e)==AKEY_EVENT_ACTION_UP&&AKeyEvent_getKeyCode(e)==AKEYCODE_BACK){page679=HOME;touch679++;h=1;}AInputQueue_finishEvent(iq679,e,h);}return 1;}
void loop679(){ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);while(run679){if(win679)draw679(win679);ALooper_pollOnce(120,nullptr,nullptr,nullptr);}}
void wc679(ANativeActivity*,ANativeWindow*w){win679=w;}void wd679(ANativeActivity*,ANativeWindow*){win679=nullptr;}void qc679(ANativeActivity*,AInputQueue*q){iq679=q;ALooper*l=ALooper_forThread();if(!l)l=ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);AInputQueue_attachLooper(q,l,1,cb679,nullptr);}void qd679(ANativeActivity*,AInputQueue*q){AInputQueue_detachLooper(q);if(iq679==q)iq679=nullptr;}void destroy679(ANativeActivity*){run679=false;if(th679.joinable())th679.join();}
}
extern "C" void ANativeActivity_onCreate(ANativeActivity*a,void*,size_t){a->callbacks->onNativeWindowCreated=wc679;a->callbacks->onNativeWindowDestroyed=wd679;a->callbacks->onInputQueueCreated=qc679;a->callbacks->onInputQueueDestroyed=qd679;a->callbacks->onDestroy=destroy679;run679=true;th679=std::thread(loop679);}
extern "C" int ra679_write(){return -403;}extern "C" int ra679_delete(){return -403;}extern "C" int ra679_restore(){return -403;}extern "C" int ra679_apply(){return -403;}extern "C" int ra679_live_order(){return -403;}extern "C" int ra679_auto_update(){return -403;}extern "C" const char* ra679_version(){return "67.9-mega-safe";}
